# -*- encoding: utf-8 -*-
{   "name" : "localización mexicana",
    "version" : "1.0",
    "depends" : [
                "account_invoice_resend_email",                 
                "account_invoice_payment_by_date_due",                              
                "account_move_line_base_tax",                      
                "account_period_and_fiscalyear",                
                "account_tax_cash_basis",             
                "accounting_reports_consol",                
                "Plan_contable",
                #"invoice_cancel",
                "sat_catalogos",                      
                "webservice",                         
                "anticipos",                 
                "einvoice_report",                             
                "pagos",
                "complementos_contabilidad",
                "rfc",  
                "ifrs_report",   
                "reporte_diot",
                "account_move_subscription",   
                                
                ],
    "author" : "QX UNIT DE MÉXICO SA DE CV",
    "description" : """

                    """,
    "website" : "http://www.qxunit.com.mx",
    "category" : "Contabilidad/Application",
    "init_xml" : [],
    "demo_xml" : [],
    "update_xml" : [],
    "test" : [],
    "images" : [],
    "auto_install": False,
    "application": True,
    "installable": True,
}
