# -*- coding: utf-8 -*-
{
    "name": "Fleet Maintenance Connector",
    "version": "15.0.1.0.0",
    "summary": """ Conecta los módulos de Flota y Mantenimiento para gestionar solicitudes y disponibilidad """,
    "author": "Jorge Chuc",
    "website": "",
    "category": "",
    "depends": [
        "base",
        "fleet",
        "maintenance",
        "mail",
        "hr",
        "product",
        "repair",
        "stock",
        "maintenance_request_repair",
        "purchase",
        "purchase_custom",
        "account",
        "base_account_budget",
        "account_fleet",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/fleet_vehicle_views.xml",
        "views/maintenance_bom_views.xml",
        "views/maintenance_equipment_category_views.xml",
        "views/maintenance_equipment_views.xml",
        "views/maintenance_request_views.xml",
        "views/repair_order_views.xml",
        "wizards/repair_to_purchase_wizard.xml",
    ],
    "application": False,
    "installable": True,
    "auto_install": False,
}
#
