# -*- coding: utf-8 -*-
{
    'name': 'Base logistic Sanmex',
    'version': '',
    'description': """ Base_logistic_sanmex Description """,
    'summary': """ Base_logistic_sanmex Summary """,
    'author': 'Jorge Chuc',
    'website': 'Muyul.mx',
    'category': '',
    'depends': ['base', 'stock','sale','product','sale_renting','barcodes'],
    "data": [
        "security/logistic_groups_access.xml",
        "views/logistic_route_views.xml",
        "views/logistic_route_menu.xml",
        "security/ir.model.access.csv",
        "views/logistic_planning_views.xml",
        "views/product_template_view.xml",
        "wizard/logistics_assign.xml",
        "views/logistic_sale_order_view.xml",
        "views/res_config_settings_view.xml",
        "views/templates.xml",
        "views/store_view_product_lot_view.xml",
        "views/stock_stage_product_views.xml",
        "views/logistics_stage_sanmex_view.xml",
        "views/sale_renting_views.xml",
        "wizard/sanmex_assign_rent_lot.xml",
        "views/stock_warehouse_views.xml",
        "reports/logistics_planning_out_view_report.xml",
        "wizard/wizard_stock_lot_state.xml",
        "views/stock_lot_log_views.xml"
    ],
    "assets": {
        'web.assets_backend': [
            'base_logistics_sanmex/static/src/scss/logistics_dasboard.scss',
            'base_logistics_sanmex/static/src/js/rent_logistics_dashboard.js',
            'base_logistics_sanmex/static/src/js/planning_logistics_dashboard.js',
            'base_logistics_sanmex/static/src/js/stock_lot_dashboard.js',
            'base_logistics_sanmex/static/src/js/registries_planning_barcode.js',
            'base_logistics_sanmex/static/src/js/planning_lot_barcode.js',
            'base_logistics_sanmex/static/src/js/quagga.js',
            'base_logistics_sanmex/static/src/js/html5-qrcode.js',
            ],
        'web.assets_qweb': [
            'base_logistics_sanmex/static/src/xml/**/*',
        ],
    },
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
